### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by h14turkiye**
Error: 
```[16:48:40 ERROR]: Error occurred while enabling telekinesis v2.3.0-1.20.1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class dev.nyon.telekinesis.MainKt
	at dev.nyon.telekinesis.listeners.BlockListenersKt.<clinit>(BlockListeners.kt:40) ~[telekinesis-paper-2.3.0-1.20.1-dev.jar:?]
	at dev.nyon.telekinesis.Main.onEnable(Main.kt:37) ~[telekinesis-paper-2.3.0-1.20.1-dev.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: RARE [in thread "Server thread"]
	at dev.nyon.telekinesis.TelekinesisEnchantment.<init>(TelekinesisEnchantment.kt:21) ~[telekinesis-paper-2.3.0-1.20.1-dev.jar:?]
	at dev.nyon.telekinesis.MainKt.<clinit>(Main.kt:18) ~[telekinesis-paper-2.3.0-1.20.1-dev.jar:?]
	at dev.nyon.telekinesis.Main.onLoad(Main.kt:31) ~[telekinesis-paper-2.3.0-1.20.1-dev.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
	... 3 more
[16:48:40 INFO]: [telekinesis] Disabling telekinesis v2.3.0-1.20.1
```

### CODE REVIEW

**Comment by h14turkiye** [comment]
All changes are not tested.

**Comment by btwonion** [comment]
merged in this relase: https://github.com/btwonion/telekinesis/releases/tag/paper-2.3.1-1.20.1
please let me know if it satisfies your expectations

**Comment by h14turkiye** [comment]
`onByDefault = false
# Uncomment this by removing '# ' to block functionality for those who don't have the required permission.
# onByDefaultPermissionRequirement = 'permission'
onByDefaultPermissionRequirement = null
onlyOnSneak = false
enchantment = true
blockDrops = true
# blockDropsPermissionRequirement = 'permission'
blockDropsPermissionRequirement = null
expDrops = true
# expDropsPermissionRequirement = 'permission'
expDropsPermissionRequirement = null
entityDrops = true
# entityDropsPermissionRequirement = 'permission'
entityDropsPermissionRequirement = null`
Toml configuration seems messy now after disabling ignoreNull in tomlconfig. Commenting seems a better way but one of them should go.

The stacktrace error 'Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: RARE [in thread "Server thread"]
' persists.

**Comment by btwonion** [comment]
let me test again

**Comment by btwonion** [comment]
when does this happen? 
after joining or instantly while starting up?

**Comment by h14turkiye** [comment]
Instantly starting. As you can see the MainKt class doesn't work.

**Comment by btwonion** [comment]
im running git-Paper-175 and it works

**Comment by h14turkiye** [comment]
[22:42:57 INFO]: Checking version, please wait...
[22:42:57 INFO]: This server is running Folia version git-Folia-"34039e3" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 34039e3)
You are 26 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
> 
This is my version. I don't see any imports in case of 'Rarity'. I'll check docs.

**Comment by btwonion** [comment]
let me test with folia

**Comment by h14turkiye** [comment]
Yes

**Comment by btwonion** [comment]
i ran the plugin in my test environment with folia now and it worked. normally this should absolutely work.
Rarity is a minecraft enum and should be available on every vanilla based servers

**Comment by btwonion** [comment]
the weird thing is that it shows you the name of the enum. normally it should look like class_1664

**Comment by h14turkiye** [comment]
It is a static field in the net.minecraft.enchantment.Enchantment class. I'm using Java 19 OpenSDK. There shouldn't be any issues. Maybe there was an error when I compiled Folia. Can you send me your version? I'll send you a dm in discord.

About the config, the confusing part was there was no option of permission requirement. And the version that was released had both the comments and the keys. My intent here was this, with ignoring null values.
```
onByDefault = false
# Uncomment this by removing '# ' to block functionality for those who don't have the required permission.
# onByDefaultPermissionRequirement = 'permission'
onlyOnSneak = false
enchantment = true
blockDrops = true
# blockDropsPermissionRequirement = 'permission'
expDrops = true
# expDropsPermissionRequirement = 'permission'
entityDrops = true
# entityDropsPermissionRequirement = 'permission'
```

**Comment by btwonion** [comment]
image
this is what it looks like atm..

**Comment by h14turkiye** [comment]
Config looks great. After recompiling issue still persists. I don't know Kotlin compiling but does replacing Rarity with Enchantment.Rarity works for you? Maybe that way it can see the inner class. Thats my last request. It seems to be an issue on my end so I will look into it personally.

**Comment by btwonion** [comment]
EnchantmentRarity is an implementation by Bukkit. this wont work on original minecraft classes

**Pull request merged**
